### ISSUE TITLE
the repository accept contributions?

### ISSUE THREAD

**Issue by KunYi** [OpenNuvoton/MA35D1_Yocto-v3.1.3#1]
I want contribution some patch for the repository.
but I don't know have any contributions policy/guide?

accpet by  github pull request?

**Comment by ychuang3** [comment]
This repository is for download only.
If you found any bugs, please let use know.
Thank you.

**Comment by KunYi** [comment]
please check this patch https://github.com/UWINGS-KUNYI/kas-ma35d1/blob/main/patches/0010-fixed-bootloader-missed-nand-ubi.patch
for avoid missed u-boot-initial-env-nand-ubi.cfg when u-boot keep in sstate
