### ISSUE TITLE
please check tf-a-ma35d1 recipse 

### ISSUE THREAD

**Issue by KunYi** [OpenNuvoton/MA35D1_Yocto-v3.1.3#2]
mabye this Line setting typo, should "MA35D1_DRAM_SIZE=0x1F800000" for 512MB?
https://github.com/OpenNuvoton/MA35D1_Yocto-v3.1.3/blob/e05210489851624ef87466e47b68ac996ba10686/meta-ma35d1/recipes-bsp/tf-a/tf-a-ma35d1_2.3.bb#L78

**Comment by ychuang3** [comment]
Yes, it is a typo error. We fixed it and will updtae later.
Thank you.
