### ISSUE TITLE
What's your building env?

### ISSUE THREAD

**Issue by champ-isaac** [OpenNuvoton/MA35D1_Yocto-v3.1.3#3]
Hello,
I'm trying to rebuild this yocto project. Could your provide building env?

**Comment by ychuang3** [comment]
Hi,

May I know who is the Nuvoton contact window for you?
I will ask him to asnwer your question. Thanks.

Jacky

**Comment by champ-isaac** [comment]
Hello,
I bought NuMaker-HMI-MA35D1-S1 in Nuvoton online store. So no contact window.
I just want to setup my IoT system and need to build my custom yocto image to support docker service.

So I need to find a Nuvoton window first?
Or you have any documents which I can refer? 

Thanks,

Isaac

**Comment by ychuang3** [comment]
Hi,

Please find the following link to get MA35D1 BSP resource:
https://github.com/OpenNuvoton/MPU-Family

The following is the link to a VMWare image for download
https://www.nuvoton.com/resource-download.jsp?tp_GUID=SW182022101516122042

Or, you can follow the UM_EN_MA35D1_Yocto.pdf  user manual to create your Yocto build environment.

[UM_EN_MA35D1_Yocto.pdf](https://github.com/OpenNuvoton/MA35D1_Yocto-v3.1.3/files/10311403/UM_EN_MA35D1_Yocto.pdf)

Best Regards,
Jacky

**Comment by champ-isaac** [comment]
> Hi,
> 
> Please find the following link to get MA35D1 BSP resource: https://github.com/OpenNuvoton/MPU-Family
> 
> The following is the link to a VMWare image for download https://www.nuvoton.com/resource-download.jsp?tp_GUID=SW182022101516122042
> 
> Or, you can follow the UM_EN_MA35D1_Yocto.pdf user manual to create your Yocto build environment.
> 
> [UM_EN_MA35D1_Yocto.pdf](https://github.com/OpenNuvoton/MA35D1_Yocto-v3.1.3/files/10311403/UM_EN_MA35D1_Yocto.pdf)
> 
> Best Regards, Jacky

It's very helpful! Thanks a lot!
